site_name: Tasmota
site_description: Documentation (Wiki) for Tasmota. Open source firmware for ESP8266 devices with easy configuration using webUI, OTA updates, automation using timers or rules, expandability and entirely local control over MQTT, HTTP, serial or KNX.
site_url: https://tasmota.github.io/docs/
edit_uri: 'https://github.com/tasmota/docs/blob/master/docs/'
# copyright: 'Copyright &copy; 2020 Tasmota Development Team'
# use_directory_urls: false

theme: 
  name: material
  # custom_dir: 'theme'
  palette:
    primary: 'blue'
    accent: 'indigo'
  features:
    - tabs
  font:
    text: Barlow
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/Ks2Kzd4'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/tasmota'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/tasmota'
nav: 
  - Bug: index.md
  - Fix1: fix.md
  - Fix2: fix2.md


markdown_extensions:
  - admonition
